# Generated by Django 3.2 on 2023-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230522_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualplan',
            name='courses',
            field=models.ManyToManyField(blank=True, to='core.Course', verbose_name='plans'),
        ),
    ]
