# Generated by Django 3.2 on 2023-05-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_individualplan_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualplan',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='plans', to='core.Course'),
        ),
    ]
